### ISSUE TITLE
Using Hardware4*.java code in another project

### ISSUE THREAD

**Issue by dbwiddis** [sarxos/secure-tokens#4]
I'm one of the developers on the [Oshi](https://github.com/dblock/oshi) project, providing cross-platform JNA-based hardware information.

A user has [requested CPU serial number](https://github.com/dblock/oshi/issues/69) and I found this project after reading your reply to [this StackOverflow post](http://stackoverflow.com/questions/1986732/how-to-get-a-unique-computer-identifier-in-java-like-disk-id-or-motherboard-id).

I'd love to just copy your [Hardware4*.java](https://github.com/sarxos/secure-tokens/tree/master/src/main/java/com/github/sarxos/securetoken/impl) files straight over to my project, with perhaps some minor modifications, but want to respect your licensing.  Is it sufficient to include your name as author with our EPL license?     Are there any other ways to get your files (releasing a jar, publishing on Maven central, etc.) without copying the source?  Would you be interested in contributing a PR yourself?

**Comment by sarxos** [comment]
Hi @dbwiddis, feel free to do what you need to do :) It's MIT so you have a wide spectrum of possible choices. If you want to avoid copying source code I can release it to Maven Central even now.

**Comment by sarxos** [comment]
@dbwiddis, just a note. Many things happen after I first wrote this piece of code and it seems like some functionalities I was depending on in the past are now deprecated (e.g. lack of HAL on Ubuntu makes `lshal` unavailable) making it hard to get SN without a `sudo` :( On Windows things does not happen to change but I'm not sure about Apples. Therefore it may be hard to have portable solution if you decide to use secure-tokens code in your project.

**Comment by dbwiddis** [comment]
Yeah, it's not so much using the code as the formalities of copying the license wording exactly.  Just wanted to run it by you first.  I actually already have a util function to do commandlines so I'm mostly only stealing the idea I hadn't thought about, which was a series of fallback attempts.  dmidecode first, lshal second, possibly cpuid.    And I'll probably replace your exceptions with default values.   I'll probably add in MAC address listing as well.
